controllers/config/defaults.go, controllers/database/app_database.go, dev/inventory-mq.yml
https://issues.redhat.com/browse/RHCLOUD-13352
=> RHCLOUD-13352 syndicate insights_id

controllers/database/app_database.go, dev/advisor-db.yaml
https://issues.redhat.com/browse/RHCLOUD-8846
=> RHCLOUD-8846 set cyndi db password in operator

deploy/operator.yml
https://issues.redhat.com/browse/RHCLOUD-14553
=> move connector template to config map

deploy/operator.yml
https://issues.redhat.com/browse/RHCLOUD-14553
https://jdbc.postgresql.org/documentation/head/connect.html#ssl
https://jdbc.postgresql.org/documentation/head/ssl-client.html
=> RHCLOUD-14553 define sslmode on the sink connector

controllers/config/defaults.go, deploy/operator.yml
https://issues.redhat.com/browse/RHCLOUD-14725
=> switch to "if" predicate property of connect-transform SMTs

controllers/config.go, controllers/config/config.go, controllers/config/config_test.go, controllers/utils/k8s.go, controllers/utils/lang.go
https://issues.redhat.com/browse/ESSNTL-686
=> ESSNTL-686 support central configuration for multi-namespace deployments

controllers/config/config.go, controllers/config/defaults.go, controllers/config/types.go, controllers/connect/connect.go, controllers/cyndipipeline_controller.go, controllers/database/database.go, deploy/operator.yml
https://issues.redhat.com/browse/ESSNTL-695
=> ESSNTL-695 configurable sslmode and sslrootcert

.github/workflows/checkimage.yaml
https://issues.redhat.com/browse/ESSNTL-3486
cc: @fijshion review please
=> Update Base image if needed to get the latest security patches

Dockerfile
RHCLOUD-23979 use ubi8-minimal image as the base for cyndi's image for security tightening
=> RHCLOUD-23979 use ubi8-minimal image as the base for cyndi's image

api/v1alpha1/cyndipipeline_types.go, config/crd/bases/cyndi.cloud.redhat.com_cyndipipelines.yaml, controllers/config/config.go, controllers/config/config_test.go, controllers/config/defaults.go, controllers/config/types.go, controllers/cyndipipeline_controller.go
This is a quick way to address this issue: https://issues.redhat.com/browse/ESSNTL-4826.
=> Add DBTableInitScript to CRD

Dockerfile
=> Updating Go to latest that works in UBI8

Dockerfile
Updating CGO_Enabled flag to 1 to test it out since it is required for FIPS
=> Update CGO Flag

controllers/cyndipipeline_controller.go, controllers/validate.go
Apparently this was wrong, we should always count all the hosts...
=> Do not count activ table hosts with the filters applied

build_catalog.sh, build_deploy.sh, build_latest_catalog.sh, build_security_catalog.sh, controllers/connect/connect.go, controllers/connect/connect_test.go, controllers/validate.go, test/crd/047-Crd-kafkaconnector.yaml
In Strimzi 38.0 they've switched to using `state` instead of `pause`. AFter deploying AMQ Streams 2.6, if `pause` is in place it causes the connectors to continuously be redeployed.
=> Kafkaconnect spec update

build_deploy.sh
Since introducing multiarch builds the security compliance builds were unable to complete successfully. This fixes the issue for those builds.
=> fix: Update security compliance builds

Dockerfile
Updating the go-toolset that we build from and removing some unneeded packages from the running image.
=> Update go toolset

.gitignore, build_catalog.sh
Uses a temp dir for the docker config to keep it out of the workspace.
=> Use temp dir for docker config

.dockerignore, build_catalog.sh
Refactors the build-script to use docker config variable.
=> refactor(ci): refactor build script

README.md, controllers/config/defaults.go, controllers/cyndipipeline_controller_test.go, controllers/integration_test.go, controllers/validation_controller_test.go, dev/inventory-api.yml, dev/inventory-db.secret.yml, dev/inventory-db.yaml, dev/inventory-mq.yml
This reverts commit 7ebea886d47e6fae9be5c4249ae1a2b7ecf5a9c8.
=> Revert "Use HBI's read-replicas rather than main DBs (#130)"

controllers/config/config.go, controllers/config/config_test.go, controllers/config/defaults.go, controllers/config/types.go, controllers/cyndipipeline_controller.go, controllers/validate.go, controllers/validation_controller.go, deploy/operator.yml
* Add default value of public
* Add deployment parameter specification to add HBI schema to config map
* Update controller logic to gather HBI schema value from config and construct inventory table name
* Add basic test cases
=> feat(rhineng-12779): Pass HBI schema using update to cyndi config map

Dockerfile
=> Update go-toolset image to 1.22.9

controllers/config/defaults.go, controllers/database/app_database.go, controllers/integration_test.go
Related slack thread: https://redhat-internal.slack.com/archives/CQFKM031T/p1748505816858949
=> Syndicate last_check_in
