RedHatInsights/cyndi-operator

controllers/config.go
controllers/config/config.go
controllers/config/config_test.go
controllers/config/parsers_test.go
controllers/connect/connect.go
controllers/connect/connect_test.go
controllers/cyndipipeline_controller.go
controllers/cyndipipeline_controller_test.go
controllers/database/app_database.go
controllers/database/app_database_test.go
controllers/database/database.go
controllers/database/database_test.go
controllers/database/test_common.go
controllers/diff.go
controllers/integration_test.go
controllers/iteration.go
controllers/metrics/metrics.go
controllers/probes.go
controllers/utils/k8s.go
controllers/utils/misc.go
controllers/validate.go
controllers/validation_controller.go
controllers/validation_controller_test.go
go.mod
main.go
test/setup.go

So that `go get` works:
```
Error: go [-e -json -compiled=true -test=false -export=false -deps=true -find=false -tags ignore_autogenerated -- ./...]: exit status 1: go: github.com/RedHatInsights/cyndi-operator@v0.1.3: parsing go.mod:
module declares its path as: cyndi-operator
but was required as: github.com/RedHatInsights/cyndi-operator
```

Use proper module name

---

Dockerfile

Reverts RedHatInsights/cyndi-operator#77.  Reverting this change because the final image should be `ubi-minimal` based and NOT distroless.

Revert "RHCLOUD-23979 use ubi8-minimal image as the base for cyndi's image"

---

Dockerfile

This change is made so that the final image uploaded to cloudservices is `ubi-minimal` based.  The previous update would make `gcr.io/distroless/static:nonroot` as the base image, which would not work for fedramp

RHCLOUD-23979 update docker file to include ubi-minimal in the final image

---

controllers/validate.go

This should improve the inconsistency ratios as retrieving the `hbiHostCount` can take significantly more time than `appHostCount`.

perf: RHINENG-3117 swap the order of the validation queries

---

build_deploy.sh

This PR adds multi arch build support to the cyndi operator build script. I worked with App SRE to get docker buildx with a multi arch builder enabled on our jenkins nodes. The build script now looks to see if a multiarch builder is there, and if so it does a multi arch build with buildx. If not, it falls back to a standard single arch amd64 build.

Multi arch (amd64 and arm64) builds

---

Dockerfile

The go toolset isn't required for the running image and increases the vulnerability footprint of the image overall. We can remove it without impacting the cyndi operator itself.

fix: remove go-toolset from running image

---

Dockerfile
build_deploy.sh

updating the go toolset to 1.20, which is most current and free of vulnerabilities.
Also removing the extra tools that are not needed for the app to work.

Update go toolset and remove debug tools

---

build_catalog.sh

It has been observed  that the `build_catalog` script is set up so that when the SC build Job runs, it write a new image over the original `image_tag` on which the commit is based. 
This update fixes that issue.

fix(build_catalog): Only Create SC Tag When Building SC Branch

---

README.md
controllers/config/defaults.go
controllers/cyndipipeline_controller_test.go
controllers/integration_test.go
controllers/validation_controller_test.go
dev/forward-ports.sh
dev/inventory-api.yml
dev/inventory-db.secret.yml
dev/inventory-db.yaml
dev/inventory-mq.yml

This PR switches out references to `host-inventory-db` for `host-inventory-read-only-db`. Makes it so Cyndi uses the read replicas rather than the main DB.

Use HBI's read-replicas rather than main DBs

---

deploy/operator.yml

This change allows the host inventory db secret to be set by a parameter instead of having to hardcode it into the configMap. It will default to the read only replica

feat: make inventory secret configurable by param

---

.github/workflows/security-scanning-workflow.yml

Enabling the `Platform Security GitHub Workflow` - This workflow provides Red Hat ConsoleDot Teams with a way to scan the containers they create in a convenient, automated, and reliable manner within their GitHub repository. The Platform Security Github Workflow lets teams get security feedback as they open Pull Requests.
REF: https://github.com/RedHatInsights/platform-security-gh-workflow

Enable Platform-Security GitHub Workflow

---

README.md
controllers/config/defaults.go
controllers/database/app_database.go

This new `syndicated` field would be useful to measure the delay between the change in the inventory DB and the actual write of the row in the application DBs. The important piece is that it is not using Kafka to measure the lag.

RHINENG-10912: add an auto-updating timestamp field on the table

---

README.md
controllers/config/defaults.go
controllers/database/app_database.go

Reverts RedHatInsights/cyndi-operator#138
Reverting because we've seen issues in Ephemeral. The logs haven't indicated why this PR would be the cause, but this warrants further investigation before attempting the merge again

Revert "RHINENG-10912: add an auto-updating timestamp field on the table"

---

build_catalog.sh

There are CVEs related to the operator source and catalog that we need to resolve. These are the latest versions of opm and go and this PR is an attempt to see if these version work

security: update opm_version and golang version in catalog

---

build_catalog.sh

Reverts RedHatInsights/cyndi-operator#142
It turns out PR 142 may have broken the build-catalog pipeline due to an OPM-related issue. I'm reverting this to see if it resolves the issue (FYI @SteveHNH)

Revert "security: update opm_version and golang version in catalog"

---

build_catalog.sh

Reverts RedHatInsights/cyndi-operator#144
The revert did not fix the issue, so I'm reverting the revert. Sorry!

Revert "Revert "security: update opm_version and golang version in catalog""

---

build_catalog.sh

* Skip the failing step as we download a new opm each build

bugfix(rhineng-12109): Resolve index build failure

---

build_catalog.sh

* revert to older opm and go for bundle creation

bugfix(rhineng-12109): Build fails with go panic

---

dev/kafka-connect.yaml

rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED
The PR replaces the old xjoin-kafka-connect-strizmi with the new `insights-kafka-connect` image used by Fedramp.  In Fedramp it appears to meet their requirements.  That's why adding it to the Cyndi-operator, which needs kafka-connect.

Use the kafka-connect image patched for security fixes and used by Fedramp

---

build_catalog.sh

Catalog is downloading its GO version.
We've bumped go in 7591d4fcb0175516fa3c31282f4190402aeaf339 and forgot to bump it for the catalog build.

Bump GO version to build catalog with

---

Makefile

CI (Jenkins) uses Go 1.22, lets try to use compatible controller and revert the big bump in 7591d4fcb0175516fa3c31282f4190402aeaf339 a bit.

Use controller-tools still compatible with go 1.22

---

Dockerfile

This will pull latest 1.23 without upgrading to 1.24 go.
This will also rebuild the operator on latest UBI image.

build(deps): Bump to latest 1.23 build image
